# [Info]
site_name: 个人主页JIEYONG # 左上角标题
site_url: https://XZ1949-10.github.io
site_author: 
site_description: 

# [UI]
## [top]
theme:
  name: material
  palette: 
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs # 编辑按钮跳转的链接

## [top-right corner]
repo_url: https://github.com/XZ1949-10.github.io # 右上角点击跳转的链接
repo_name: XZ1949-10.github.io # 右上角的名字
## [bottom-left corner]
copyright: Copyright &copy; 
## [bottom-right corner]
extra:
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/448214169
      name: Bilibili  # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/zhangzhiwei-zzw
      name: GitHub | zhangzhiwei-zzw
      

# [Navigtion]
nav:
  - C/C++: 
    - C++/index.md
    - Lambda表达式: C++/Lambda表达式.md
    - C/C++回调函数: C++/C++回调函数.md
    - 多维数组的创建: C++/动态开辟多维数组.md
  - Java:
    - Java/index.md
    - Spring: Java/Spring/Spring5.md
    - SpringMVC: Java/SpringMVC/SpringMVCNotes.md
    - MyBatis: Java/mybatis/MyBatis.pdf
    - MyBatisPlus: Java/mybatis/MyBatisPlus.pdf
    - SpringBoot: Java/SpringBoot/SpringBoot.md
    - SpringSecurity: Java/SpringSecurity/SpringSecurity.md
    - 设计模式: Java/designpattern/designpattern.md
  - Python: 
    - Python/index.md
    - 深度学习: Python/deeplearning/index.html
  - ROS2学习: 
    - ROS2学习/index.md
    - ROS2-Gazebo仿真: ROS2学习/ROS2-Gazebo仿真.md
    - ROS2-rviz2显示模型: ROS2学习/ROS2-rviz2显示模型.md
    - ROS2-URDF建模: ROS2学习/ROS2-URDF建模.md
    - tf2坐标变换工具: ROS2学习/tf2坐标变换工具.md
    - ROS2课程资料: ROS2学习/ROS2/index.html
    - Apollo课程资料: ROS2学习/Cyber_RT/index.html
    
  - 博客: 
    - blogs/index.md
    - vue3快速入门: blogs/vue3快速上手.md
    - Lambda表达式: C++/Lambda表达式.md
    - 多维数组的创建: blogs/动态开辟多维数组.md
    - solidity基础: blogs/solidity基础.md
    - C/C++回调函数: C++/C++回调函数.md
    - 强化学习基本概念1: blogs/强化学习1(基本概念).md
    - 强化学习基本概念2: blogs/强化学习2(价值学习).md
    - 强化学习基本概念3: blogs/强化学习3(策略学习).md
    - 强化学习基本概念4: blogs/强化学习4(Actor-Critic算法).md
    - 普通用户权限运行Docker: blogs/普通用户权限运行Docker.md
    - Docker常用命令: blogs/Docker常用命令.md
    - DWA局部路径规划: blogs/DWA局部路径规划算法.md
  - 关于: about.md

    
    
    
# [Extensions]
plugins:
  - search: # 现在还不支持中文搜索 支持之后可以设置语言
    # insider已经支持中文的分词搜索了 https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
        - ja
  - tags # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
markdown_extensions:
  - pymdownx.arithmatex: # latex支持
      generic: true
  - attr_list # 给图片后面添加{width="300"}设置大小
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
extra_javascript:
  # latex支持
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docs/mkdocs/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > docs/mkdocs/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  - mkdocs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0
extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
  - mkdocs/css/unordered-list-symbols.css # multiplt unordered list symbols
